name: Build Project on Python 3.10
run-name: Python 3.10
on: [push]
jobs:
  python3-10-cpu:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Install
          run: pip install -e .
        - name: Prepare for tests
          run: |
                mkdir -p data/temp/toys
        - name: Test
          run: |
                make test
